### ISSUE TITLE
Fetcher failure for URL: 'file:///proj/yocto/dnndk/zynqmp_latest in ZCU102_base

### ISSUE THREAD

**Issue by Roywastie** [Xilinx/Vitis_Embedded_Platform_Source#10]
Fetcher failure for URL: 'file:///proj/yocto/dnndk/zynqmp_latest when during make in the petalinux part
[platform.log](https://github.com/Xilinx/Vitis_Embedded_Platform_Source/files/4953905/platform.log)

**Comment by imrickysu** [comment]
Please check https://github.com/Xilinx/Vitis-AI/issues/118.

Workaround: download PetaLinux sstate-cache and set in petalinux project config to enable sstate-cache before petalinux-build.

**Comment by luyufan498** [comment]
> Please check [Xilinx/Vitis-AI#118](https://github.com/Xilinx/Vitis-AI/issues/118).
> 
> Workaround: download PetaLinux sstate-cache and set in petalinux project config to enable sstate-cache before petalinux-build.

Plz, could  u make it clearer? I have checked the config file, I find that the CONFIG_YOCTO_NETWORK_SSTATE_FEEDS_URL is set  exactly as mentioned in the link. 

How can I download and enable the sstate-cache?

**Comment by yangye8** [comment]
Do you modify/add/remove any packages in Petalinux part in 2020.1 base platform? Or you just use an original one

**Comment by Roywastie** [comment]
I used the original one, but got the same error everyone is getting

**Comment by luyufan498** [comment]
> Do you modify/add/remove any packages in Petalinux part in 2020.1 base platform? Or you just use an original one

original one, nothing modified

**Comment by imrickysu** [comment]
Please try these steps and see whether it can pass compilation:

1. download "aarch64 sstate-cache" (12GB) from PetaLinux download page: https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-design-tools.html
2. Extract  sstate_aarch64_2020.1.tar.gz: `tar -xzf sstate_aarch64_2020.1.tar.gz`
3. Update PetaLinux project configuration to use extracted sstate cache
**Method A**: Open petalinux/project-spec/configs/config file and update CONFIG_YOCTO_LOCAL_SSTATE_FEEDS_URL to
```
CONFIG_YOCTO_LOCAL_SSTATE_FEEDS_URL="/path/to/sstate_aarch64_2020.1/aarch64"
```

**Method B**: run `petalinux-config`, go to "Yocto Settings" -> "Local sstate cache settings" -> Input the path of sstate cache, e.g. "/path/to/sstate_aarch64_2020.1/aarch64" (no quote)

**Comment by luyufan498** [comment]
> Please try these steps and see whether it can pass compilation:
> 
> 1. download "aarch64 sstate-cache" (12GB) from PetaLinux download page: https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-design-tools.html
> 2. Extract  sstate_aarch64_2020.1.tar.gz: `tar -xzf sstate_aarch64_2020.1.tar.gz`
> 3. Update PetaLinux project configuration to use extracted sstate cache
>    **Method A**: Open petalinux/project-spec/configs/config file and update CONFIG_YOCTO_LOCAL_SSTATE_FEEDS_URL to
> 
> ```
> CONFIG_YOCTO_LOCAL_SSTATE_FEEDS_URL="/path/to/sstate_aarch64_2020.1/aarch64"
> ```
> 
> **Method B**: run `petalinux-config`, go to "Yocto Settings" -> "Local sstate cache settings" -> Input the path of sstate cache, e.g. "/path/to/sstate_aarch64_2020.1/aarch64" (no quote)

to be honest, I  have already tried this way (use petalinux-config). 
However, it doesn't work.
I also tried the 30+GB "downloads" file.
Not working neither.

But I will build a new project and try again,  I will leave my comments if there is any update

**Comment by luyufan498** [comment]
![1](https://user-images.githubusercontent.com/6166841/89175450-b60ba200-d57f-11ea-8830-0598c7fe9734.png)
![2](https://user-images.githubusercontent.com/6166841/89175454-b6a43880-d57f-11ea-9c80-c21b5cf3fcc1.png)
![3](https://user-images.githubusercontent.com/6166841/89175455-b6a43880-d57f-11ea-992d-3cb04e6aa202.png)

**Comment by luyufan498** [comment]
Just same errors

**Comment by earthshadow** [comment]
I tried to generate the zcu104_base and also met this issues.

I found out that I can generate the platform successfully with the command "make all COMMON_RFS_KRNL_SYSROOT=FALSE" when I remove the "xrt" at line 4 in the file https://github.com/Xilinx/Vitis_Embedded_Platform_Source/blob/master/Xilinx_Official_Platforms/zcu104_base/petalinux/Makefile .

Somehow, I cannot figure out how the command "petalinux-config -c xrt --silentconfig" works inside the petalinux project. The UG1144/UG1157 doesn't have any details about the "xrt" component. Therefore, I cannot ensure that bypassing the "petalinux-config -c xrt" will get the compatible platform to use with Vitis-AI.

May I know where to look for more details about the command "petalinux-config -c xrt --silentconfig" ?

**Comment by imrickysu** [comment]
It looks like this issue is related to XRT recipes, because XRT is in RDEPENDS of dnndkdeploy. We're investigating the recompile trigger conditions. 

For now, a workaround is to remove petalinux/meta-user/recipe-xrt directory. It specifies XRT version to be 2020.1. Actually the default XRT version in PetaLinux is 2020.1 So this specification is safe to be removed.

**Comment by imrickysu** [comment]
I verified that removing `petalinux-config -c xrt --silentconfig` from makefile can workaround this issue.

`petalinux-config -c xrt --silentconfig` downloads XRT source code and makes bitbake thinks it's updated. It triggers dnndkdeploy compile from source.

**Comment by luyufan498** [comment]
Will it disable XRT ？I need to run vitis-ai,  should I do the same?

**Comment by imrickysu** [comment]
XRT will still be available in rootfs. 

This change stops calling petalinux-config for xrt/zocl so that petalinux will stop assume that xrt is changed.

**Comment by luyufan498** [comment]
So，it means that we cant modify XRT?

**Comment by imrickysu** [comment]
No, you cannot change XRT if you'd like to have dnndkdeploy in rootfs.

If you'd like to modify XRT source code, it can be done in XRT repo and build with https://github.com/Xilinx/XRT/blob/master/build/build_edge.sh. The generated RPM can be installed in any system with DNF enabled (base platform has this feature)

**Comment by chvamshi-xilinx** [comment]
This issue is fixed now. We have made changes to the makefile which fixed the issue.
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/commit/56eb728ecb9fb1b9e54cfc1e69b66aad7f578c60
