### ISSUE TITLE
ZCU102 DFX ：Run 'impl_1' has not been launched. Unable to open, when make xsa

### ISSUE THREAD

**Issue by luyufan498** [Xilinx/Vitis_Embedded_Platform_Source#16]
![image](https://user-images.githubusercontent.com/6166841/90010466-cb777f00-dc97-11ea-9987-22ceb21ab4e1.png)

Error occurs, when I try to make xsa for ZCU102 DFX
 
By the way,I want use ZCU104 with DFX feature in my design.  Is there any document about how to build a zcu104 dfx platform ?

**Comment by doonny** [comment]
you might need to set correct license for vivado

**Comment by luyufan498** [comment]
> you might need to set correct license for vivado

thx, u r right
