### ISSUE TITLE
Vitis Embedded platform development for Acceleration - Creating Software development

### ISSUE THREAD

**Issue by gkrislara** [Xilinx/Vitis_Embedded_Platform_Source#2]
I have found issue while building petalinux for zcu102 for accelerated application development

[The issue is posted in the forum](https://forums.xilinx.com/t5/Embedded-Linux/Vitis-Embedded-platform-development-for-Acceleration-Creating/td-p/1058481)

I am reported error when executing the command petalinux-build
It is reported that there is a syntax error at system-user.dtsi file

compatible="xlnx,zocl" is being highlighted as an error

where am I going wrong?

**Comment by zohourih** [comment]
For the record, this issue has already been addressed in the forum thread and can probably be closed.
