### ISSUE TITLE
How to build Platform for other Board(such as ZedBoard)

### ISSUE THREAD

**Issue by sunshine411** [Xilinx/Vitis_Embedded_Platform_Source#20]
Hi.
        I am using zedboard as a development platform, how can I make a system environment that can run Vitis AI applications?
Thanks

**Comment by imrickysu** [comment]
To create custom platforms, please refer to the tutorial here: https://github.com/Xilinx/Vitis-In-Depth-Tutorial/tree/master/Vitis_Platform_Creation
