### ISSUE TITLE
Build error on zcu104_base 2020.2

### ISSUE THREAD

**Issue by pcjustin** [Xilinx/Vitis_Embedded_Platform_Source#25]
Hi,

I built zcu104_base on 2020.2, but I got the error message. Because of failed to copy bl31.elf and boot.scr.

Any patch to fix the problem

**Comment by pcjustin** [comment]
Can anyone help me to figure out the problem?

**Comment by imrickysu** [comment]
Hi @pcjustin , could you provide the command you used to generate zcu104_base and what's the detailed error message your encountered?

**Comment by pcjustin** [comment]
Hi @imrickysu I used `make all COMMON_RFS_KRNL_SYSROOT=FALSE` to build the project and it failed the following line on `sw/petalinux/Makefile` line 27 and line 28. Because it didn't generate `boot.scr` and `bl31.elf` on `images/linux`.

cp -f images/linux/boot.scr ${SW_COMP_DIR}/platform/image/boot.scr
cp -f images/linux/bl31.elf ${SW_COMP_DIR}/platform/boot/bl31.elf

Updated:
I modified the `sw/Makefile` to disable `rm -rf $(BUILD_DIR)` and it passed. That's strange.
