### ISSUE TITLE
how could I download embedded platform Vitis source of Ultra96v2 board

### ISSUE THREAD

**Issue by JianmingTONG** [Xilinx/Vitis_Embedded_Platform_Source#26]
As title, Thanks!

**Comment by imrickysu** [comment]
Ultra96 is an Avnet board. 

I found these references for you to create one platform for Ultra96

https://www.hackster.io/mohammad-hosseinabady2/ultra96v2-linux-based-platform-in-xilinx-vitis-2020-1-06f226

https://github.com/KeitetsuWorks/Vitis-Platform-Ultra96-V2-v2020.1

Xilinx has tutorials for creating custom Vitis platforms.

https://github.com/Xilinx/Vitis-Tutorials -> Vitis Platform Creation
