### ISSUE TITLE
md files not clear on DPU vs BASE platform difference

### ISSUE THREAD

**Issue by gguasti** [Xilinx/Vitis_Embedded_Platform_Source#5]
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms/zcu102_dpu
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms/zcu102_base

What is the difference between BASE platform and DPU platform? the md file does not explain ..

**Comment by wilderfield** [comment]
Agree with @gguasti the md file is just a copy, and does not explain the difference. 

I don't see any logic that inserts a dpu into the zcu102_dpu or zcu104_dpu.

**Comment by imrickysu** [comment]
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/blob/2019.2/Xilinx_Official_Platforms/zcu102_dpu/release_notes.md provides the details of how zcu102_dpu platform is created based on zcu102_base.

From 2020.1, all base platforms are capable of running Vitis-AI applications. Please refer to https://github.com/Xilinx/Vitis-AI and UG1414 for more info.
